sudo: required
services:
  - docker

env:
  - REACT_APP_API_URL=https://pico-gram.herokuapp.com

before_install:
  - docker build -t byalif/pico-front -f DockerFile.dev .

script:
  - docker run byalif/pico-front npm run test -- --coverage